#!/usr/bin/env python3
"""Generate original MAS companion themes. Store-safe, no third-party IP."""

from __future__ import annotations

import json
from pathlib import Path

from companion_shapes import svg_for
from companion_sounds import write_sounds

ROOT = Path(__file__).resolve().parent.parent
THEMES = ROOT / "themes"

CHARACTERS = [
    {
        "id": "halo",
        "zh": "光环",
        "zh_tw": "光環",
        "en": "Halo",
        "desc": "A round cream spirit with a gold ring and a coral scarf.",
        "body": "#f4e6c8",
        "stroke": "#c9ae86",
        "feet": "#d7c09a",
        "eye": "#3b2a1a",
        "accent": "#e07a5f",
        "voice": "en-US-AriaNeural",
        "rate": "+12%",
        "pitch": "+8Hz",
        "sfx": "bell",
        "confirm_text": "Glow.",
        "complete_text": "Light's ready.",
    },
    {
        "id": "sprout",
        "zh": "豆芽",
        "zh_tw": "豆芽",
        "en": "Sprout",
        "desc": "A little seedling with two new leaves.",
        "body": "#9fce6e",
        "stroke": "#6a9a45",
        "feet": "#7aad4d",
        "eye": "#2c3d1c",
        "accent": "#4f8a32",
        "voice": "en-US-AnaNeural",
        "rate": "+18%",
        "pitch": "+16Hz",
        "sfx": "leaf",
        "confirm_text": "Grow.",
        "complete_text": "Fresh start.",
    },
    {
        "id": "persimmon",
        "zh": "柿子",
        "zh_tw": "柿子",
        "en": "Persimmon",
        "desc": "A plump persimmon with a green calyx.",
        "body": "#e07a3d",
        "stroke": "#b85a24",
        "feet": "#c9662c",
        "eye": "#3d2414",
        "accent": "#4a7c3a",
        "voice": "en-US-JennyNeural",
        "rate": "+10%",
        "pitch": "+4Hz",
        "sfx": "pluck",
        "confirm_text": "Ripe.",
        "complete_text": "Sweet enough.",
    },
    {
        "id": "ink",
        "zh": "墨点",
        "zh_tw": "墨點",
        "en": "Ink",
        "desc": "A wet ink blot with a shiny highlight.",
        "body": "#2c2c2e",
        "stroke": "#151516",
        "feet": "#1d1d1f",
        "eye": "#f2efe8",
        "accent": "#4b5563",
        "voice": "en-GB-ThomasNeural",
        "rate": "-4%",
        "pitch": "-6Hz",
        "sfx": "drip",
        "confirm_text": "Blot.",
        "complete_text": "Ink is dry.",
    },
    {
        "id": "crescent",
        "zh": "月牙",
        "zh_tw": "月牙",
        "en": "Crescent",
        "desc": "A smiling crescent moon.",
        "body": "#f0d26a",
        "stroke": "#c9a43a",
        "feet": "#ddc57d",
        "eye": "#4a3b18",
        "accent": "#f7f1d2",
        "voice": "en-GB-LibbyNeural",
        "rate": "+6%",
        "pitch": "+10Hz",
        "sfx": "glass",
        "confirm_text": "Night.",
        "complete_text": "Moon is up.",
    },
    {
        "id": "teapot",
        "zh": "茶盏",
        "zh_tw": "茶盞",
        "en": "Teapot",
        "desc": "A small celadon teapot.",
        "body": "#7eaea0",
        "stroke": "#4f7d72",
        "feet": "#628f84",
        "eye": "#22362f",
        "accent": "#d7c4a3",
        "voice": "en-GB-SoniaNeural",
        "rate": "-2%",
        "pitch": "-2Hz",
        "sfx": "ceramic",
        "confirm_text": "Sip.",
        "complete_text": "Tea is poured.",
    },
    {
        "id": "crane",
        "zh": "纸鹤",
        "zh_tw": "紙鶴",
        "en": "Crane",
        "desc": "A folded paper crane.",
        "body": "#f7f3ea",
        "stroke": "#cfc6b6",
        "feet": "#e4dccb",
        "eye": "#3b3428",
        "accent": "#d9c8a8",
        "voice": "en-US-AvaNeural",
        "rate": "+14%",
        "pitch": "+12Hz",
        "sfx": "paper",
        "confirm_text": "Fold.",
        "complete_text": "Wings are set.",
    },
    {
        "id": "nimbus",
        "zh": "雨云",
        "zh_tw": "雨雲",
        "en": "Nimbus",
        "desc": "A rain cloud with falling drops.",
        "body": "#d7e5f3",
        "stroke": "#9bb3c9",
        "feet": "#b7c9db",
        "eye": "#2a3b4c",
        "accent": "#6f92b3",
        "voice": "en-CA-ClaraNeural",
        "rate": "+4%",
        "pitch": "+2Hz",
        "sfx": "rain",
        "confirm_text": "Drip.",
        "complete_text": "Clouds cleared.",
    },
    {
        "id": "lantern",
        "zh": "灯笼",
        "zh_tw": "燈籠",
        "en": "Lantern",
        "desc": "A red festival lantern with a tassel.",
        "body": "#c23b3b",
        "stroke": "#8d2424",
        "feet": "#a52e2e",
        "eye": "#3b1414",
        "accent": "#e4c36a",
        "voice": "en-US-MichelleNeural",
        "rate": "+8%",
        "pitch": "+6Hz",
        "sfx": "wood",
        "confirm_text": "Bright.",
        "complete_text": "Lantern's lit.",
    },
    {
        "id": "cactus",
        "zh": "青刺",
        "zh_tw": "青刺",
        "en": "Cactus",
        "desc": "A two-armed cactus with one pink flower.",
        "body": "#5f8f5c",
        "stroke": "#3d633b",
        "feet": "#4d774b",
        "eye": "#1f301e",
        "accent": "#e07a9a",
        "voice": "en-US-GuyNeural",
        "rate": "+6%",
        "pitch": "-4Hz",
        "sfx": "snap",
        "confirm_text": "Prick.",
        "complete_text": "Still standing.",
    },
    {
        "id": "bao",
        "zh": "包子",
        "zh_tw": "包子",
        "en": "Bao",
        "desc": "A plump steamed bun with pinched folds.",
        "body": "#f3ead7",
        "stroke": "#c9b89a",
        "feet": "#ddcfb4",
        "eye": "#4a3b28",
        "accent": "#d9c29a",
        "voice": "en-US-EmmaNeural",
        "rate": "+10%",
        "pitch": "+8Hz",
        "sfx": "steam",
        "confirm_text": "Steam.",
        "complete_text": "Bun is ready.",
    },
    {
        "id": "starfish",
        "zh": "海星",
        "zh_tw": "海星",
        "en": "Starfish",
        "desc": "A five-pointed starfish.",
        "body": "#e28a68",
        "stroke": "#b45d3f",
        "feet": "#c96f4e",
        "eye": "#3d2218",
        "accent": "#f0c3a8",
        "voice": "en-AU-NatashaNeural",
        "rate": "+8%",
        "pitch": "+5Hz",
        "sfx": "bubble",
        "confirm_text": "Tide.",
        "complete_text": "Star is home.",
    },
    {
        "id": "turtle",
        "zh": "石龟",
        "zh_tw": "石龜",
        "en": "Turtle",
        "desc": "A stone turtle with a mossy shell.",
        "body": "#7d8b73",
        "stroke": "#55614d",
        "feet": "#66735d",
        "eye": "#24301e",
        "accent": "#9aa68d",
        "voice": "en-US-ChristopherNeural",
        "rate": "-8%",
        "pitch": "-8Hz",
        "sfx": "stone",
        "confirm_text": "Slow.",
        "complete_text": "Step by step.",
    },
    {
        "id": "fox",
        "zh": "赤狐",
        "zh_tw": "赤狐",
        "en": "Fox",
        "desc": "A small red fox with a bushy tail.",
        "body": "#d17a3a",
        "stroke": "#9a5424",
        "feet": "#b8662c",
        "eye": "#3d2414",
        "accent": "#f4efe6",
        "voice": "en-US-RogerNeural",
        "rate": "+16%",
        "pitch": "+10Hz",
        "sfx": "yip",
        "confirm_text": "Hey.",
        "complete_text": "Caught it.",
    },
    {
        "id": "owl",
        "zh": "夜鸮",
        "zh_tw": "夜鴞",
        "en": "Owl",
        "desc": "A stout owl with ear tufts.",
        "body": "#8b7355",
        "stroke": "#5e4c38",
        "feet": "#735f46",
        "eye": "#1c1610",
        "accent": "#f0e6c8",
        "voice": "en-GB-RyanNeural",
        "rate": "-6%",
        "pitch": "-10Hz",
        "sfx": "hoot",
        "confirm_text": "Who.",
        "complete_text": "Watch is done.",
    },
    {
        "id": "acorn",
        "zh": "橡果",
        "zh_tw": "橡果",
        "en": "Acorn",
        "desc": "A shiny acorn with a textured cap.",
        "body": "#c48a4a",
        "stroke": "#8b5a2b",
        "feet": "#a46e36",
        "eye": "#3d2414",
        "accent": "#6b4423",
        "voice": "en-US-EricNeural",
        "rate": "+2%",
        "pitch": "-3Hz",
        "sfx": "nut",
        "confirm_text": "Tap.",
        "complete_text": "Seed is safe.",
    },
    {
        "id": "snow",
        "zh": "雪团",
        "zh_tw": "雪團",
        "en": "Snow",
        "desc": "A two-ball snowman with coal buttons.",
        "body": "#f4f7fb",
        "stroke": "#c5d0dc",
        "feet": "#dde5ee",
        "eye": "#2a3340",
        "accent": "#e07a7a",
        "voice": "en-US-SteffanNeural",
        "rate": "+4%",
        "pitch": "+3Hz",
        "sfx": "crunch",
        "confirm_text": "Soft.",
        "complete_text": "Snow is packed.",
    },
]


def theme_json(char: dict) -> dict:
    return {
        "schemaVersion": 1,
        "name": {"zh": char["zh"], "zh-TW": char["zh_tw"], "en": char["en"]},
        "author": "Addsum",
        "version": "1.0.0",
        "description": char["desc"],
        "customization": {"petTint": False},
        "viewBox": {"x": -15, "y": -25, "width": 45, "height": 45},
        "layout": {
            "contentBox": {"x": -4, "y": -6, "width": 23, "height": 24},
            "centerX": 7.5,
            "baselineY": 17,
            "visibleHeightRatio": 0.58,
            "baselineBottomRatio": 0.05,
        },
        "eyeTracking": {
            "enabled": True,
            "states": ["idle"],
            "eyeRatioX": 0.5,
            "eyeRatioY": 0.5,
            "maxOffset": 0.8,
            "bodyScale": 0.25,
            "shadowStretch": 0.15,
            "shadowShift": 0.3,
            "ids": {"eyes": "eyes-js", "body": "body-js", "shadow": "shadow-js"},
            "shadowOrigin": "7.5px 15px",
        },
        "states": {
            "idle": ["idle-follow.svg"],
            "thinking": ["thinking.svg"],
            "working": ["working.svg"],
            "juggling": ["working.svg"],
            "error": {"fallbackTo": "attention"},
            "attention": ["attention.svg"],
            "notification": {"fallbackTo": "attention"},
            "sweeping": {"fallbackTo": "attention"},
            "carrying": {"fallbackTo": "attention"},
            "sleeping": ["sleeping.svg"],
            "waking": ["idle-follow.svg"],
        },
        "sleepSequence": {"mode": "direct"},
        "timings": {"mouseIdleTimeout": 20000, "mouseSleepTimeout": 60000},
        "hitBoxes": {
            "default": {"x": -3, "y": -6, "w": 22, "h": 22},
            "sleeping": {"x": -3, "y": 4, "w": 22, "h": 12},
        },
        "sleepingHitboxFiles": ["sleeping.svg"],
        "sounds": {"complete": "complete.mp3", "confirm": "confirm.mp3"},
        "miniMode": {"supported": False},
        "objectScale": {"widthRatio": 1.9, "heightRatio": 1.3, "offsetX": -0.45, "offsetY": -0.25},
    }


def write_character(char: dict) -> None:
    theme_dir = THEMES / char["id"]
    assets = theme_dir / "assets"
    sounds = theme_dir / "sounds"
    assets.mkdir(parents=True, exist_ok=True)
    sounds.mkdir(parents=True, exist_ok=True)
    (theme_dir / "theme.json").write_text(json.dumps(theme_json(char), ensure_ascii=False, indent=2) + "\n")
    mapping = {
        "idle-follow.svg": "idle",
        "thinking.svg": "thinking",
        "working.svg": "working",
        "attention.svg": "attention",
        "sleeping.svg": "sleeping",
    }
    for filename, kind in mapping.items():
        (assets / filename).write_text(svg_for(char, kind))
    write_sounds(char, sounds)


def main() -> None:
    for char in CHARACTERS:
        write_character(char)
        print(char["id"], char["zh"])


if __name__ == "__main__":
    main()
